### ISSUE TITLE
apply form post 404

### ISSUE THREAD

**Issue by jmsv** [whitep4nth3r/hell.com#1]
hello I would love to join hell.com

however the form POST on the [apply.astro](https://github.com/whitep4nth3r/hell.com/blob/main/src/pages/apply.astro) page is 404ing

thank you

**Comment by whitep4nth3r** [comment]
The site isn’t finished yet. And it’s also kind of a throwback joke to the
original hell.com. 🙃

**Comment by jmsv** [comment]
didn't know about hell.com, TIL!

noticed it redirects to a bible website nowadays though 😄
